- name: Get latest wordpress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /opt/wordpress.zip
    mode: 640

- unarchive:
    src: /opt/wordpress.zip
    dest: /opt/
    remote_src: True
  register: dir_name

- name: Copy files to data
  shell: cp -r /opt/wordpress/* /opt/data

- name: Create and start mysql
  docker_container:
    name: database
    image: mysql
    state: started
    force_kill: yes
    volumes:
    - /opt/db:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: easypasswd

- name: Create and start php-fpm
  docker_container:
    name: backend
    image: bitnami/php-fpm
    state: started
    force_kill: yes
    volumes:
      - /opt/data:/var/www
      - /opt/php5:/etc/php5:ro
    links:
      - "database:mysql"

- name: Create and start nginx
  docker_container:
    name: frontend
    image: nginx
    state: started
    force_kill: yes
    volumes:
      - /opt/nginx:/etc/nginx:ro
    volumes_from:
      - backend
    expose:
      - "80:80"
    links:
      - "backend:php"
