- name: Create and start mysql
  docker_container:
    name: database
    image: mysql
    state: started
    force_kill: yes
    volumes:
    - /opt/db:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: myeasyrootpasswd
      MYSQL_DATABASE: mywordpress
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myeasypasswd


- name: Create and start Wordpress
  docker_container:
    name: Wordpress
    image: wordpress
    state: started
    force_kill: yes
    ports:
      - '8080:80'
    links:
      - "database:database"
    volumes:
      - /opt/wordpress:/var/www/html
    env:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: myeasypasswd
      WORDPRESS_DB_NAME: mywordpress
